### ISSUE TITLE
有一条信息您还未查收

### ISSUE THREAD

**Issue by superferryman** [jingangxin36/Tetris#1]
发现了一个奇怪的bug，在
![emm](https://user-images.githubusercontent.com/37292028/43621983-834b117e-970c-11e8-8ef4-eec15399c2b6.png)
这个位置，还有，美工是你自己做的吗，介意我拿去用吗（非商用）。

**Comment by jingangxin36** [comment]
@superferryman 你好, 这个bug是什么时候会出现的呢? 比如说什么操作之后, 是偶尔出现还是必现??
UI是我上网找免费图标资源和自己做的, 可以拿去用
